### PR TITLE
properly set rulename

### PR DESCRIPTION
**Pull request by emgeee**

### CODE REVIEW

**Comment by puzrin** [comment]
That's invalid. `ruleName` is defined on plugin call here https://github.com/emgeee/markdown-it-for-inline/blob/54cc7c09f236032075d917a46f080462ea29ba7b/index.js#L4

**Comment by puzrin** [comment]
Ups... sorry, i've missunderstood. Thanks for the fix!

**Comment by emgeee** [comment]
:) no problem, was about to make my case!

**Comment by puzrin** [comment]
Released with your fix

**Pull request merged**
